### ISSUE TITLE
Langchain_agent: 'LLM' object has no attribute 'prompt'

### ISSUE THREAD

**Issue by ha-zhcool** [OpenHands/OpenHands#190]
**Describe the bug**
Backend stuck with following errors after performing some steps and should be restarted:
```
Error in loop Error condensing thoughts: 'LLM' object has no attribute 'prompt'
Traceback (most recent call last):
  File "/home/user/AI/OpenDevin/agenthub/langchains_agent/utils/monologue.py", line 29, in condense
    response = llm.prompt(prompt)
               ^^^^^^^^^^
AttributeError: 'LLM' object has no attribute 'prompt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/AI/OpenDevin/opendevin/controller/__init__.py", line 61, in start_loop
    finished = await self.step(i)
               ^^^^^^^^^^^^^^^^^^
  File "/home/user/AI/OpenDevin/opendevin/controller/__init__.py", line 81, in step
    action: Action = self.agent.step(state)
                     ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/AI/OpenDevin/agenthub/langchains_agent/__init__.py", line 165, in step
    self._add_event(d)
  File "/home/user/AI/OpenDevin/agenthub/langchains_agent/__init__.py", line 87, in _add_event
    self.monologue.condense(self.llm)
  File "/home/user/AI/OpenDevin/agenthub/langchains_agent/utils/monologue.py", line 33, in condense
    raise RuntimeError(f"Error condensing thoughts: {e}")
RuntimeError: Error condensing thoughts: 'LLM' object has no attribute 'prompt'
Exited before finishing
```
**Steps to Reproduce**
1. provide project instructions
2. wait for the error to happen after some steps depending on the context
3.

**Expected behavior**
It's expected to continue with the next step
**Actual behavior**
progress is interrupted and the backend should be restarted
**Additional context**
Pulled the latest version, running on Ubuntu, updated the requirements

**Comment by rbren** [comment]
Reproduced this, and fixed here: https://github.com/OpenDevin/OpenDevin/pull/191

If you check out that branch, you should have better luck 😄 Hopefully we can get it merged soon

**Comment by rbren** [comment]
Should be fixed now!
