### ISSUE TITLE
Support podman

### ISSUE THREAD

**Issue by cool9203** [OpenHands/OpenHands#5325]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Describe the bug and reproduction steps

When version check will error with podman.  
Seem like only support docker, and version check always only check docker version,  
have any chance to support podman?

```
podman run -d -p 16845:3000 \
        --privileged \
        --network slirp4netns:allow_host_loopback=true \
        -e SANDBOX_RUNTIME_CONTAINER_IMAGE=docker.all-hands.dev/all-hands-ai/runtime:0.14-nikolaik \
        -e WORKSPACE_MOUNT_PATH=$WORKSPACE_BASE \
        -e LOG_ALL_EVENTS=true \
        -v $WORKSPACE_BASE:/opt/workspace_base:z \
        -v /run/user/1000/podman/podman.sock:/var/run/docker.sock:Z \
        --name openhands \
        docker.all-hands.dev/all-hands-ai/openhands:0.14
```

### OpenHands Installation

Docker command in README

### OpenHands Version

0.14

### Operating System

Linux

### Logs, Errors, Screenshots, and Additional Context

```
Starting OpenHands...
Running OpenHands as root
INFO:     Started server process [5]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:3000 (Press CTRL+C to quit)
INFO:     10.0.2.100:52030 - "GET /app HTTP/1.1" 200 OK
INFO:     10.0.2.100:52034 - "GET /locales/en/translation.json HTTP/1.1" 200 OK
INFO:     10.0.2.100:52048 - "GET /favicon.ico HTTP/1.1" 200 OK
INFO:     10.0.2.100:52054 - "GET /config.json HTTP/1.1" 200 OK
INFO:     10.0.2.100:52070 - "GET /api/options/models HTTP/1.1" 200 OK
INFO:     10.0.2.100:52076 - "GET /api/options/agents HTTP/1.1" 200 OK
INFO:     10.0.2.100:52080 - "GET /api/options/security-analyzers HTTP/1.1" 200 OK
INFO:     ('10.0.2.100', 52088) - "WebSocket /ws" [accepted]
09:28:50 - openhands:ERROR: auth.py:27 - Invalid token
INFO:     connection open
INFO:     connection closed
INFO:     ('10.0.2.100', 39926) - "WebSocket /ws" [accepted]
09:28:52 - openhands:INFO: listen.py:357 - New session: b1ed8308-a8bc-45f3-8513-3ce10f86786d
INFO:     connection open
09:28:52 - openhands:INFO: codeact_agent.py:87 - Function calling not enabled for model ollama/llama3.1. Mocking function calling via prompting.
09:28:53 - openhands:ERROR: agent_session.py:94 - Error starting session: <class 'RuntimeError'>
Traceback (most recent call last):
  File "/app/openhands/server/session/agent_session.py", line 92, in _start_thread
    asyncio.run(self._start(*args), debug=True)
  File "/usr/local/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/app/openhands/server/session/agent_session.py", line 108, in _start
    await self._create_runtime(
  File "/app/openhands/server/session/agent_session.py", line 186, in _create_runtime
    self.runtime = runtime_cls(
                   ^^^^^^^^^^^^
  File "/app/openhands/runtime/impl/eventstream/eventstream_runtime.py", line 186, in __init__
    self.runtime_builder = DockerRuntimeBuilder(self.docker_client)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/openhands/runtime/builder/docker.py", line 21, in __init__
    raise RuntimeError('Docker server version must be >= 18.09 to use BuildKit')
RuntimeError: Docker server version must be >= 18.09 to use BuildKit
```

podman version: `4.6.2`

### If you find this feature request or enhancement useful, make sure to add a 👍 to the issue

**Comment by mamoodi** [comment]
I'm going to change this to an enhancement because it's asking support for podman which is new functionality.

**Comment by pathquester** [comment]
Was about to ask the same thing, podman is by design daemonless and rootless and although there is a rootless version of Docker as well, there is no reason not to support both.

**Comment by andrewginns** [comment]
Related to this issue which became stale https://github.com/All-Hands-AI/OpenHands/issues/2651

Using the same command as before where `docker` is a `podman` alias
```
docker run -it \
    --pull=always \
    --privileged \
    -e SANDBOX_RUNTIME_CONTAINER_IMAGE=ghcr.io/all-hands-ai/runtime:main-nikolaik \
    -e SANDBOX_USER_ID=$(id -u) \
    -e WORKSPACE_MOUNT_PATH=$WORKSPACE_BASE \
    -v $WORKSPACE_BASE:/opt/workspace_base:z \
    -v /run/user/502/podman/podman.sock:/var/run/docker.sock:Z \
    -p 3008:3000 \
    --name openhands-app-$(date +%Y%m%d%H%M%S) \
    ghcr.io/all-hands-ai/openhands:main
 ```
I get this result after adding a model API key and sending some instructions to the model.
```
INFO:     10.88.0.3:60984 - "GET /assets/terminal-_JfXwz37.js HTTP/1.1" 200 OK
INFO:     ('10.88.0.3', 32782) - "WebSocket /socket.io/?EIO=4&transport=websocket" [accepted]
17:02:58 - openhands:INFO: listen_socket.py:22 - sio:connect: Oc1IJEsCersb-253AAAB
INFO:     10.88.0.3:60986 - "GET /config.json HTTP/1.1" 200 OK
17:02:58 - openhands:INFO: listen_socket.py:64 - New session: Oc1IJEsCersb-253AAAB
17:02:58 - openhands:INFO: manager.py:220 - start_new_local_session:Oc1IJEsCersb-253AAAB
17:02:58 - openhands:INFO: codeact_agent.py:88 - Function calling not enabled for model openai/o1-mini. Mocking function calling via prompting.
17:02:58 - openhands:INFO: shutdown_listener.py:37 - _register_signal_handlers
17:02:58 - openhands:INFO: shutdown_listener.py:41 - _register_signal_handlers:main_thread
INFO:     10.88.0.3:60984 - "GET /assets/terminal-CFbL2ovg.css HTTP/1.1" 200 OK
17:02:58 - openhands:ERROR: agent_session.py:99 - Error starting session: <class 'RuntimeError'>
Traceback (most recent call last):
  File "/app/openhands/server/session/agent_session.py", line 97, in _start_thread
    asyncio.run(self._start(*args), debug=True)
  File "/usr/local/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/app/openhands/server/session/agent_session.py", line 115, in _start
    await self._create_runtime(
  File "/app/openhands/server/session/agent_session.py", line 193, in _create_runtime
    self.runtime = runtime_cls(
                   ^^^^^^^^^^^^
  File "/app/openhands/runtime/impl/eventstream/eventstream_runtime.py", line 186, in __init__
    self.runtime_builder = DockerRuntimeBuilder(self.docker_client)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/openhands/runtime/builder/docker.py", line 22, in __init__
    raise RuntimeError('Docker server version must be >= 18.09 to use BuildKit')
RuntimeError: Docker server version must be >= 18.09 to use BuildKit
```

**Comment by kenkoooo** [comment]
The root cause of this issue is that the Python Docker client returns the version of Podman when Podman is used instead of Docker. Currently, Podman’s version is 5.x, which does not satisfy the ">= 18.09" version constraint. To address this, we need to revise the logic for checking BuildKit compatibility so that it does not rely on the version number.

**Comment by enyst** [comment]
@onurcanozavci That's cool!

This was fixed by https://github.com/All-Hands-AI/OpenHands/pull/6778 and it should be in the next release, please tell if that is not the case or if you have thoughts about it.

**Comment by fmoorhof** [comment]
@aa956 
> Not resolved yet:

>    Correct permissions for mounted directories for sandbox runtime.

Do you mean this error while spawning a new container with the sandbox?
`Internal Server Error ("make cli opts(): making volume mountpoint for volume /app/workspace: mkdir /app: permission denied")`

What worked for me was:
`SANDBOX_VOLUMES=$(realpath ./workspace):/app/workspace:rw`
alternatively you might try: `SANDBOX_VOLUMES=$(realpath ./workspace):/app/workspace:Z`

Thanks for your steps, its working fine for me now:)

**Comment by aa956** [comment]
@fmoorhof 

Thank you, works now.

Looks like permission problem was resolved by removing `-e SANDBOX_USER_ID=$(id -u)` from the command line.

Now files in ./workspace are created as owned by my user.
With `SANDBOX_USER_ID` set files were created using different random uid-s on each restart of the runtime.

**Comment by mamoodi** [comment]
Is this supported now? Some folks seem to have got it working so want to know where we are with this?

**Comment by llamantino** [comment]
@mamoodi Yes, it's working (tested on stock Ubuntu 24.04.2 LTS). It needs a page in the docs explaining how to get it working, as there are significant differences to work around.

**Comment by Kurtisone** [comment]
Didn´t update but yes, it works on SteamOS too 

Below my script : 

```
#!/bin/bash
VERSION=0.47

# Launch socket
systemctl --user is-active --quiet podman.socket || systemctl --user start podman.socket

# Ddl runtime
podman pull docker.all-hands.dev/all-hands-ai/runtime:$VERSION-nikolaik

# Here we go !
podman run -it --rm --pull=always -e SANDBOX_RUNTIME_CONTAINER_IMAGE=docker.all-hands.dev/all-hands-ai/runtime:$VERSION-nikolaik -e LOG_ALL_EVENTS=true -v $XDG_RUNTIME_DIR/podman/podman.sock:/var/run/docker.sock -v ~/.openhands-state:/.openhands-state -p 3000:3000 --add-host host.docker.internal:host-gateway --name openhands-app docker.all-hands.dev/all-hands-ai/openhands:$VERSION
```

**Comment by KenMacD** [comment]
@Kurtisone the volume path should probably be updated in that command, and [it changed in `0.44`](https://docs.all-hands.dev/usage/local-setup#start-the-app): `-v ~/.openhands:/.openhands`

**Comment by AndesKrrrrrrrrrrr** [comment]
I got podman working on rootless Podman with a few important flags:
- `SANDBOX_VOLUMES` env, with SELinux relabeling (`:Z`)
- ` --security-opt label=disable` to allow Podman socket mounting inside the container (see [RedHat blog](https://www.redhat.com/en/blog/podman-inside-container))

```bash
export OPENHANDS_VERSION=0.43
export OPENHANDS_RUNTIME=docker.all-hands.dev/all-hands-ai/runtime:$OPENHANDS_VERSION-nikolaik
export OPENHANDS_IMAGE=docker.all-hands.dev/all-hands-ai/openhands:$OPENHANDS_VERSION

FLAGS=(
  -it
  --rm
  -e "SANDBOX_RUNTIME_CONTAINER_IMAGE=$OPENHANDS_RUNTIME"
  # NOTE: `:Z` mount flag fixes SELinux permission errors
  -e "SANDBOX_VOLUMES=$PWD:/workspace:Z"
  -e LOG_LEVEL=debug
  -e DEBUG=true
  -e LOG_ALL_EVENTS=true
  # NOTE: Use Docker host env, but strip protocol prefix
  -v "${DOCKER_HOST#*://}:/var/run/docker.sock"
  # NOTE: Updated volume mount
  -v ~/.openhands:/.openhands
  --security-opt label=disable
  -p 3000:3000
  --add-host host.docker.internal:host-gateway
  --name openhands-app
  "$OPENHANDS_IMAGE"
)

podman pull "$OPENHANDS_RUNTIME"
podman pull "$OPENHANDS_IMAGE"
podman run "${FLAGS[@]}"
```

**Comment by acsezen** [comment]
> Was about to ask the same thing, podman is by design daemonless and rootless and although there is a rootless version of Docker as well, there is no reason not to support both.

Highly agree with this comment and suggest to move to podman and drop docker support.

**Comment by acsezen** [comment]
> I got podman working on rootless Podman with a few important flags:
> 
>     * `SANDBOX_VOLUMES` env, with SELinux relabeling (`:Z`)
> 
>     * ` --security-opt label=disable` to allow Podman socket mounting inside the container (see [RedHat blog](https://www.redhat.com/en/blog/podman-inside-container))
> 
> 
> export OPENHANDS_VERSION=0.43
> export OPENHANDS_RUNTIME=docker.all-hands.dev/all-hands-ai/runtime:$OPENHANDS_VERSION-nikolaik
> export OPENHANDS_IMAGE=docker.all-hands.dev/all-hands-ai/openhands:$OPENHANDS_VERSION
> 
> FLAGS=(
>   -it
>   --rm
>   -e "SANDBOX_RUNTIME_CONTAINER_IMAGE=$OPENHANDS_RUNTIME"
>   # NOTE: `:Z` mount flag fixes SELinux permission errors
>   -e "SANDBOX_VOLUMES=$PWD:/workspace:Z"
>   -e LOG_LEVEL=debug
>   -e DEBUG=true
>   -e LOG_ALL_EVENTS=true
>   # NOTE: Use Docker host env, but strip protocol prefix
>   -v "${DOCKER_HOST#*://}:/var/run/docker.sock"
>   # NOTE: Updated volume mount
>   -v ~/.openhands:/.openhands
>   --security-opt label=disable
>   -p 3000:3000
>   --add-host host.docker.internal:host-gateway
>   --name openhands-app
>   "$OPENHANDS_IMAGE"
> )
> 
> podman pull "$OPENHANDS_RUNTIME"
> podman pull "$OPENHANDS_IMAGE"
> podman run "${FLAGS[@]}"

Can some part of it moved to config maybe? I see some runtime settings in config.toml like runtime_startup_env_vars.

**Comment by sheepdestroyer** [comment]
Up to fight stale label xD

**Comment by sheepdestroyer** [comment]
```
> I got podman working on rootless Podman with a few important flags:
> 
> * `SANDBOX_VOLUMES` env, with SELinux relabeling (`:Z`)
> * ` --security-opt label=disable` to allow Podman socket mounting inside the container (see [RedHat blog](https://www.redhat.com/en/blog/podman-inside-container))
> 
> export OPENHANDS_VERSION=0.43
> export OPENHANDS_RUNTIME=docker.all-hands.dev/all-hands-ai/runtime:$OPENHANDS_VERSION-nikolaik
> export OPENHANDS_IMAGE=docker.all-hands.dev/all-hands-ai/openhands:$OPENHANDS_VERSION
> 
> FLAGS=(
>   -it
>   --rm
>   -e "SANDBOX_RUNTIME_CONTAINER_IMAGE=$OPENHANDS_RUNTIME"
>   # NOTE: `:Z` mount flag fixes SELinux permission errors
>   -e "SANDBOX_VOLUMES=$PWD:/workspace:Z"
>   -e LOG_LEVEL=debug
>   -e DEBUG=true
>   -e LOG_ALL_EVENTS=true
>   # NOTE: Use Docker host env, but strip protocol prefix
>   -v "${DOCKER_HOST#*://}:/var/run/docker.sock"
>   # NOTE: Updated volume mount
>   -v ~/.openhands:/.openhands
>   --security-opt label=disable
>   -p 3000:3000
>   --add-host host.docker.internal:host-gateway
>   --name openhands-app
>   "$OPENHANDS_IMAGE"
> )
> 
> podman pull "$OPENHANDS_RUNTIME"
> podman pull "$OPENHANDS_IMAGE"
> podman run "${FLAGS[@]}"
```
@AndesKrrrrrrrrrrr I confirm this works great.

**Comment by GeoDerp** [comment]
I got to a slightly different solution, posting if it helps 
```bash
# --- Configuration ---
# Set the version of OpenHands to be used.
export OPENHANDS_VERSION=0.59

# Define the local directory for the OpenHands workspace in the user's home.
export OPENHANDS_DIR="$HOME/openhands"

# Define the container images using the public Docker Hub registry.
export OPENHANDS_RUNTIME="docker.all-hands.dev/all-hands-ai/runtime:${OPENHANDS_VERSION}-nikolaik"
export OPENHANDS_IMAGE="docker.all-hands.dev/all-hands-ai/openhands:${OPENHANDS_VERSION}"

# --- Prerequisites Setup ---
echo "Creating directories..."
mkdir -p "$OPENHANDS_DIR"
mkdir -p "$HOME/.openhands"
sudo chcon -Rt container_file_t "$HOME/openhands"

export HOST_UID=$(id -u)
export HOST_GID=$(id -g)

# --- Podman Run Flags ---
FLAGS=(
  -it
  --rm
  -e "SANDBOX_TYPE=ssh"
  -e "SANDBOX_USER=root"
  -e "SANDBOX_PASSWORD=openhands"
  -e "ACTION_EXECUTION_SERVER_URL=http://host.docker.internal:5000"
  -e "SANDBOX_RUNTIME_CONTAINER_IMAGE=$OPENHANDS_RUNTIME"
  -e "SANDBOX_VOLUMES=$OPENHANDS_DIR:/workspace"
  -e LOG_LEVEL=debug
  -e DEBUG=true
  -e LOG_ALL_EVENTS=true
  -v "${XDG_RUNTIME_DIR}/podman/podman.sock:/var/run/docker.sock:Z"
  -v "$HOME/.openhands:/.openhands:Z"
  --security-opt label=disable
  -p 3000:3000
  --add-host host.docker.internal:host-gateway
  --name openhands-app
)

# --- Execution ---
echo "Pulling necessary container images..."
podman pull "$OPENHANDS_RUNTIME"
podman pull "$OPENHANDS_IMAGE"

echo "Starting OpenHands container with SSH sandbox..."
podman run "${FLAGS[@]}" "$OPENHANDS_IMAGE"
```

however my setup isnt fully functional. Using ramalama as my model runner:
  openai/granite-4.0-h
  http://192.168.0.2:8080/v1
but getting no luck (error: the request exceeds the available context size. try increasing the context size or enable context shift)
