### ISSUE TITLE
Support OrbStack

### ISSUE THREAD

**Issue by IngLP** [OpenHands/OpenHands#5326]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Describe the bug and reproduction steps

Orbstack is one of the beat methods to run docker on MacOs: https://orbstack.dev/

OpenHands fails to work in OrbStack:

```
11:50:01 - openhands:ERROR: eventstream_runtime.py:382 - [runtime 2c72873c-723c-41c2-906f-ef8a99fe3b0b] Error: Instance openhands-runtime-2c72873c-723c-41c2-906f-ef8a99fe3b0b FAILED to start container!

11:50:01 - openhands:INFO: eventstream_runtime.py:237 - [runtime 2c72873c-723c-41c2-906f-ef8a99fe3b0b] Container started: openhands-runtime-2c72873c-723c-41c2-906f-ef8a99fe3b0b. VSCode URL: None
ERROR:asyncio:Future exception was never retrieved
future: <Future finished exception=AttributeError("'NoneType' object has no attribute 'logs'")>
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/openhands/server/session/agent_session.py", line 92, in _start_thread
    asyncio.run(self._start(*args), debug=True)
  File "/usr/local/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/app/openhands/server/session/agent_session.py", line 108, in _start
    await self._create_runtime(
  File "/app/openhands/server/session/agent_session.py", line 196, in _create_runtime
    await self.runtime.connect()
  File "/app/openhands/runtime/impl/eventstream/eventstream_runtime.py", line 242, in connect
    self.log_buffer = LogBuffer(self.container, self.log)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/openhands/runtime/impl/eventstream/eventstream_runtime.py", line 75, in __init__
    self.log_generator = container.logs(stream=True, follow=True)
                         ^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'logs'
```

### OpenHands Installation

Docker command in README

### OpenHands Version

0.14.3

### Operating System

MacOS

**Comment by mamoodi** [comment]
Going to change this to an "enhancement" rather than a bug because this is adding new functionality.
