### ISSUE TITLE
[Bug]: FAILED to start container

### ISSUE THREAD

**Issue by IngLP** [OpenHands/OpenHands#5382]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Describe the bug and reproduction steps

Install latest Docker Desktop on Mac 15.1. Run the command:
```
docker run -it --rm --pull=always \           
    -e SANDBOX_RUNTIME_CONTAINER_IMAGE=docker.all-hands.dev/all-hands-ai/runtime:0.14.3-nikolaik \
    -e SANDBOX_USER_ID=$(id -u) \
    -e WORKSPACE_MOUNT_PATH=. \
    -v .:/opt/workspace_base \
    -e LOG_ALL_EVENTS=true  \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -p 3001:3000 \
    --add-host host.docker.internal:host-gateway \
    --name openhands-app \
    docker.all-hands.dev/all-hands-ai/openhands:0.14.3
```

Enter the UI, issue any command, and the issue will appear in the logs - no container can be started:

```
12:27:54 - openhands:ERROR: eventstream_runtime.py:382 - [runtime 14067bd6-788e-4c8f-bca3-eb01bc1b7300] Error: Instance openhands-runtime-14067bd6-788e-4c8f-bca3-eb01bc1b7300 FAILED to start container!

12:27:54 - openhands:INFO: eventstream_runtime.py:237 - [runtime 14067bd6-788e-4c8f-bca3-eb01bc1b7300] Container started: openhands-runtime-14067bd6-788e-4c8f-bca3-eb01bc1b7300. VSCode URL: None
ERROR:asyncio:Future exception was never retrieved
future: <Future finished exception=AttributeError("'NoneType' object has no attribute 'logs'")>
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/openhands/server/session/agent_session.py", line 92, in _start_thread
    asyncio.run(self._start(*args), debug=True)
  File "/usr/local/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/app/openhands/server/session/agent_session.py", line 108, in _start
    await self._create_runtime(
  File "/app/openhands/server/session/agent_session.py", line 196, in _create_runtime
    await self.runtime.connect()
  File "/app/openhands/runtime/impl/eventstream/eventstream_runtime.py", line 242, in connect
    self.log_buffer = LogBuffer(self.container, self.log)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/openhands/runtime/impl/eventstream/eventstream_runtime.py", line 75, in __init__
    self.log_generator = container.logs(stream=True, follow=True)
                         ^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'logs'
```

### OpenHands Installation

Docker command in README

### OpenHands Version

0.14.3

### Operating System

MacOS

**Comment by mamoodi** [comment]
Can you try deleting all your docker images associated with OpenHands, and then just to test the basics, see if you can run the default docker command please?

```
docker run -it --pull=always \
    -e SANDBOX_RUNTIME_CONTAINER_IMAGE=docker.all-hands.dev/all-hands-ai/runtime:0.14-nikolaik \
    -e LOG_ALL_EVENTS=true \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -p 3000:3000 \
    --add-host host.docker.internal:host-gateway \
    --name openhands-app \
    docker.all-hands.dev/all-hands-ai/openhands:0.14
```

I wasn't able to reproduce this.

**Comment by mamoodi** [comment]
Try this documentation: https://docs.all-hands.dev/modules/usage/runtimes#connecting-to-your-filesystem

Basically in your terminal set WORKSPACE_BASE.
Then add those three lines mentioned in the doc. Let me know if that works.

**Comment by mamoodi** [comment]
But I don't think a relative path is acceptable. It needs to be an absolute path.
